name: GitHub Actions Trigger Queue for Auto-Grading
run-name: ${{ github.actor }} is submitting their ğŸ  home ğŸ’ª work for ğŸ¤– bot ğŸ“ grading on GitHub Actions ğŸš€
on: [push]
jobs:
  Submit-For-Autograding:
    runs-on: ubuntu-latest
    env:
      AZURE_SERVICEBUS_CONNECTION_STRING: ${{ secrets.AZURE_SERVICEBUS_CONNECTION_STRING }}
      AZURE_SERVICEBUS_QUEUE: ${{ vars.AZURE_SERVICEBUS_QUEUE }}
    steps:
      - run: echo "DT=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - run: echo "ğŸ—“ï¸ The job was triggerd on ${{ env.DT }}."
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "ğŸªˆ The queue name is ${{ env.AZURE_SERVICEBUS_QUEUE }}."
      - run: pip install azure-servicebus-cli
      - run: azsb send --queue ${{ env.AZURE_SERVICEBUS_QUEUE }} --message '{"timestamp":"${{ env.DT }}","cmd":"graderbot","repo_url":"${{ github.repository }}"}'
      - run: echo "ğŸ Message sent to the grading bot! This job's status is ${{ job.status }}."

